apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: elf0pij1y-go 
  janus-idp.io/tekton: elf0pij1y-go
  backstage.io/kubernetes-id: elf0pij1y-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: elf0pij1y-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml