apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: elf0pij1y-go
  janus-idp.io/tekton: elf0pij1y-go
  backstage.io/kubernetes-id: elf0pij1y-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: elf0pij1y-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
